### ISSUE TITLE
entity 리펙토링

### ISSUE THREAD

**Issue by devMtn30** [memory-makers/rolling-paper-api#12]
### ISSUE
- type : refactor

### TODO
- [x] card entity 수정
- [x] paper entity 수정
- [x] sticker entity 수정
- [x] Lombok.config 에서 특정 Annotation 제한하기

### 기타
- entitiy에서 setter 제거 및 builder 패턴 적용
- Lombok.config 에서 특정 Annotation 제한하기
lombok.setter.flagUsage=error // @Setter 사용시 컴파일에러
lombok.data.flagUsage=error // @Data 사용시 컴파일에러

**Comment by devMtn30** [comment]
https://developer-ping9.tistory.com/225
참고
