### ISSUE TITLE
프로젝트 리팩토링

### ISSUE THREAD

**Issue by devMtn30** [memory-makers/rolling-paper-api#2]
### ISSUE
- type : refactor

### TODO
- [x] REST API구조로 변경
  - 컨트롤러, 서비스 등 네이밍 컨벤션에 맞춰서 변경
- [x] Custom Exception
- [x] 예외 처리(NPE 등) 최적화
- [x] 유지보수를 위한 Log 추가
### 기타
- 빠른 배포를 위해 테스트 코드는 리팩토링이 끝나면 Junit 학습 후 테스트 코드 추가 예정(10월 中)
