### ISSUE TITLE
API 예외 처리

### ISSUE THREAD

**Issue by devMtn30** [memory-makers/rolling-paper-api#22]
### ISSUE
- type : feat

### TODO
- [x] 회원 예외 처리
  - 사용자 정보 조회
  - 닉네임 설정
  - 사용자 닉네임 조회

- [x] 페이퍼 예외 처리
  - 롤링페이퍼 생성
  - 롤링페이퍼 목록
  - 롤링페이퍼 보기
  - 롤링페이퍼 수정
  - paperUrl을 통해 paperId 조회
  - 롤링페이퍼 삭제
  - paperId를 통해 nickname 조회
 
- [x] 카드 예외 처리
  - 카드 생성
  - 카드 조회
  
- [x] 스티커 예외 처리
  - 스티커 편집
  - 스티커 목록 보기

### 기타
- 11.04까지 처리하여 주말 간 프론트엔드에서 처리할 시간 만들기

**Comment by devMtn30** [comment]
테스트 후 메인 배포 예정
